name: akurateco_flutter
homepage: https://akurateco.com/
description: "A simple Akurateco API wrapper"

version: 1.0.0+1

environment:
  sdk: ^3.0.0



dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  webview_flutter: ^4.12.0
  crypto: ^3.0.6


dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
    uses-material-design: true


